version: '3.8'

services:
    database:
        image: postgres:latest
        container_name: role_events
        ports:
            - ${DB_PORT}:5432
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks:
            - default
    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        environment:
            - DB_HOST=role_events
            - DB_PORT=5432
        volumes:
            - ./:/var/www
            - ./docker/php/confs/php.ini:/usr/local/etc/php/php.ini
        networks:
            - default
        depends_on:
            - database
    nginx:
        image: nginx:latest
        ports:
            - ${DEV_PORT}:80
        environment:
            - SERVER_NAME=${APP_DOMAIN}
        volumes:
            - ./:/var/www
            - ./docker/nginx/confs:/etc/nginx/conf.d
        networks:
            - default
        depends_on:
            - app
    queue:
        build:
            context: ./docker/php
            dockerfile: queue.Dockerfile
        environment:
            - DB_HOST=role_events
            - DB_PORT=5432
        volumes:
            - ./:/var/www
            - ./docker/php/confs/php.ini:/usr/local/etc/php/php.ini
        networks:
            - default
        depends_on:
            - app
networks:
    default:
