version: '3.8'

services:
    database:
        image: postgres:latest
        container_name: role_events
        ports:
            - ${DB_PORT}:5432
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks:
            - default
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: app
        environment:
            - DB_HOST=role_events
            - DB_PORT=5432
        networks:
            - default
        depends_on:
            - database
    nginx:
        build:
            context: .
            dockerfile: Dockerfile
            target: web
        ports:
            - ${DEV_PORT}:80
        networks:
            - default
    queue:
        build:
            context: .
            dockerfile: Dockerfile
            target: app-queue
        environment:
            - DB_HOST=role_events
            - DB_PORT=5432
        networks:
            - default
networks:
    default:
